DATA:
    data_name: PPMI
    deg4feat: True

DATALOADER:
    NUM_WORKERS: 0
    BATCH_SIZE: 16

MODEL:
    num_hidden: 512
    num_layers: 2
    nhead: 4
    activation: prelu
    attn_drop: 0.1
    feat_drop: 0.2
    norm: layernorm
    pooler: mean
    beta_schedule: sigmoid
    beta_1: 0.000335
    beta_T: 0.03379
    T: 728

SOLVER:
    optim_type: adamw
    optim_type_f: adamw
    alpha: 1
    decay: 30
    LR: 0.000292
    weight_decay: 0.0005
    MAX_EPOCH: 100

DEVICE: cuda
seeds:
    - 11
eval_T:
    - 50
    - 100
    - 300

